#!/bin/bash

# Check if the CFILE variable is set
if [ -z "$CFILE" ]; then
    echo "CFILE variable is not set"
    exit 1
fi

# Run the C file through the preprocessor and save the result
gcc -E "$CFILE" -o c
